/**
 * Clipboard history — pure rules (no fs, no electron), shared by the capture
 * loop (app-init.js) and the store behind the Clipboard view
 * (clipboard-store.js).
 */

const IMAGE_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".heic",
  ".heif",
  ".tif",
  ".tiff",
  ".bmp",
]);

/** At most this many files are kept from one Finder copy. */
const MAX_FILES_PER_COPY = 10;
/** Photos copied in Finder are kept up to this size; bigger ones keep only their name. */
const MAX_PHOTO_FILE_MB = 50;
/** Other files (PDFs, documents…) are kept only when the user turns it on, up to this size. */
const MAX_KEPT_FILE_MB = 100;
/** Files are opt-in: they're kept in full and can take a lot of space. */
const DEFAULT_CAPTURE = Object.freeze({ keepFiles: false, monitor: true });

const DAY_MS = 86_400_000;
const MB = 1024 * 1024;

/** "Keep history for" choices in days; 0 keeps everything. */
const KEEP_DAYS_OPTIONS = [0, 7, 30, 90];
/** "Images can use up to" choices in MB; 0 means no limit. */
const IMAGE_CAP_OPTIONS_MB = [0, 200, 500, 1024, 2048];
/** Defaults never delete text; images stop at 1 GB, oldest first. */
const DEFAULT_RETENTION = Object.freeze({ keepDays: 0, maxImageMB: 1024 });

function extensionOf(filePath) {
  const base = String(filePath ?? "").split(/[\\/]/).pop() ?? "";
  const dot = base.lastIndexOf(".");
  return dot > 0 ? base.slice(dot).toLowerCase() : "";
}

function isImageFile(filePath) {
  return IMAGE_EXTENSIONS.has(extensionOf(filePath));
}

/** `file:///Users/me/My%20Photo.jpg` → `/Users/me/My Photo.jpg`; null for anything else. */
function fileUrlToPath(url) {
  const raw = String(url ?? "").replace(/\0/g, "").trim();
  if (!raw.startsWith("file://")) return null;
  try {
    const parsed = new URL(raw);
    if (parsed.protocol !== "file:") return null;
    const decoded = decodeURIComponent(parsed.pathname);
    return decoded || null;
  } catch {
    return null;
  }
}

/** Paths from macOS's `NSFilenamesPboardType` property list (every file in one Finder copy). */
function parseFilenamesPlist(xml) {
  const out = [];
  const re = /<string>([\s\S]*?)<\/string>/g;
  let match;
  while ((match = re.exec(String(xml ?? ""))) !== null) {
    const value = match[1]
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&apos;/g, "'")
      .replace(/&amp;/g, "&")
      .trim();
    if (value.startsWith("/")) out.push(value);
  }
  return out;
}

/** Entry metadata arrives as a JSON string from the database; tolerate objects and junk. */
function parseMetadata(metadata) {
  if (metadata && typeof metadata === "object") return metadata;
  if (typeof metadata !== "string" || !metadata) return {};
  try {
    const parsed = JSON.parse(metadata);
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}

function isImageMetadata(metadata) {
  return parseMetadata(metadata).type === "image";
}

/**
 * `keepFiles`: copied files are kept in full (opt-in). `monitor`: the
 * clipboard is watched at all (on unless the user turned it off; saved in
 * main so a restart can't quietly turn it back on).
 */
function normalizeCapture(raw) {
  const obj = raw && typeof raw === "object" ? raw : {};
  return { keepFiles: obj.keepFiles === true, monitor: obj.monitor !== false };
}

// ── Copies that are never kept ───────────────────────────────────────────

/**
 * Clipboard formats that say "don't remember this copy". macOS: the
 * nspasteboard.org markers (1Password, Bitwarden, KeePassXC, Apple
 * Passwords…) and older app-specific ones. Windows: the formats KeePass,
 * Bitwarden and 1Password set to stay out of Clipboard History. Linux:
 * KDE's password-manager hint (KeePassXC).
 */
const PRIVATE_CLIPBOARD_FORMATS = Object.freeze({
  darwin: Object.freeze([
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "net.antelle.keeweb",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
  ]),
  win32: Object.freeze(["ExcludeClipboardContentFromMonitorProcessing", "Clipboard Viewer Ignore"]),
  linux: Object.freeze(["x-kde-passwordManagerHint"]),
});

/** Windows formats holding a DWORD; 0 means "keep out of history / the cloud". */
const WIN32_ZERO_MEANS_PRIVATE = Object.freeze(["CanIncludeInClipboardHistory", "CanUploadToCloudClipboard"]);

/**
 * Whether the current copy asks not to be remembered. `has(format)` and
 * `readBuffer(format)` are Electron's clipboard functions. When the check
 * itself fails the copy counts as private: missing one copy is the safe
 * mistake, keeping a password is not.
 */
function isPrivateClipboard({ platform, has, readBuffer }) {
  if (typeof has !== "function") return false;
  try {
    for (const format of PRIVATE_CLIPBOARD_FORMATS[platform] || []) {
      if (has(format)) return true;
    }
    if (platform === "win32") {
      for (const format of WIN32_ZERO_MEANS_PRIVATE) {
        if (!has(format)) continue;
        const value = typeof readBuffer === "function" ? readBuffer(format) : null;
        if (!value || value.length < 4 || value.readUInt32LE(0) === 0) return true;
      }
    }
    return false;
  } catch {
    return true;
  }
}

/** Password managers: nothing copied while one of them is in front is kept. */
const PASSWORD_MANAGER_BUNDLE_IDS = Object.freeze([
  "com.1password.1password",
  "com.agilebits.onepassword7",
  "com.agilebits.onepassword-osx",
  "com.bitwarden.desktop",
  "org.keepassxc.keepassxc",
  "com.apple.keychainaccess",
  "com.apple.Passwords",
  "com.lastpass.LastPass",
  "com.dashlane.Dashlane",
  "com.dashlane.dashlanephonefinal",
  "in.sinew.Enpass-Desktop",
  "com.nordpass.macos.NordPass",
  "com.keepersecurity.passwordmanager",
  "com.proton.pass",
  "me.proton.pass.electron",
]);

/** Terminals: their text "field" is the whole scrollback (commands, printed secrets). */
const TERMINAL_BUNDLE_IDS = Object.freeze([
  "com.apple.Terminal",
  "com.googlecode.iterm2",
  "dev.warp.Warp-Stable",
  "net.kovidgoyal.kitty",
  "org.alacritty",
  "io.alacritty",
  "com.github.wez.wezterm",
  "co.zeit.hyper",
  "com.mitchellh.ghostty",
  "com.raphaelamorim.rio",
]);

/** Apps whose text fields are never read after a dictation (auto-learn). */
function isPrivateInputApp(bundleId) {
  return (
    typeof bundleId === "string" &&
    (PASSWORD_MANAGER_BUNDLE_IDS.includes(bundleId) || TERMINAL_BUNDLE_IDS.includes(bundleId))
  );
}

function isPasswordManagerApp(sourceApp) {
  const bundleId = sourceApp && typeof sourceApp.bundleId === "string" ? sourceApp.bundleId : "";
  return bundleId !== "" && PASSWORD_MANAGER_BUNDLE_IDS.includes(bundleId);
}

/** Well-known secret formats, found anywhere in the copied text. */
const SECRET_PATTERNS = Object.freeze([
  ["private key", /-----BEGIN [A-Z0-9 ]*PRIVATE KEY(?: BLOCK)?-----/],
  ["AWS key", /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/],
  ["GitHub token", /\b(?:gh[pousr]_[A-Za-z0-9]{36,}|github_pat_[A-Za-z0-9_]{22,})/],
  ["GitLab token", /\bglpat-[A-Za-z0-9_-]{20,}/],
  ["API key", /\bsk-(?:proj-|ant-|or-v1-|svcacct-)?[A-Za-z0-9_-]{20,}/],
  ["API key", /\bgsk_[A-Za-z0-9]{40,}/],
  ["API key", /\bAIza[0-9A-Za-z_-]{35}/],
  ["API key", /\b[rs]k_(?:live|test)_[A-Za-z0-9]{16,}/],
  ["token", /\bxox[abeoprs]-[A-Za-z0-9-]{10,}/],
  ["token", /\bnpm_[A-Za-z0-9]{36}\b/],
  ["token", /\bhf_[A-Za-z0-9]{30,}/],
  ["token", /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/],
]);

let bip39Words = null;
function isBip39Word(word) {
  if (!bip39Words) bip39Words = new Set(require("./vault/bip39-english.js"));
  return bip39Words.has(word);
}

/** 12–24 words, every one from the BIP39 list: a wallet or vault recovery phrase. */
function isRecoveryPhrase(text) {
  const words = text.trim().toLowerCase().split(/\s+/);
  if (![12, 15, 18, 21, 24].includes(words.length)) return false;
  return words.every(isBip39Word);
}

function luhnValid(digits) {
  let sum = 0;
  for (let i = 0; i < digits.length; i++) {
    let d = digits.charCodeAt(digits.length - 1 - i) - 48;
    if (i % 2 === 1) {
      d *= 2;
      if (d > 9) d -= 9;
    }
    sum += d;
  }
  return sum % 10 === 0;
}

/** 13–19 digits (spaces or dashes allowed) that pass the Luhn check. */
function isCardNumber(run) {
  const digits = run.replace(/[ -]/g, "");
  return digits.length >= 13 && digits.length <= 19 && !/^(\d)\1+$/.test(digits) && luhnValid(digits);
}

const CARD_RUN = /(^|[^\d])((?:\d[ -]?){12,18}\d)(?!\d)/g;

/** A card number anywhere in the text. */
function containsCardNumber(text) {
  for (const match of text.matchAll(CARD_RUN)) if (isCardNumber(match[2])) return true;
  return false;
}

function shannonBitsPerChar(text) {
  const counts = new Map();
  for (const ch of text) counts.set(ch, (counts.get(ch) || 0) + 1);
  let bits = 0;
  for (const n of counts.values()) {
    const p = n / text.length;
    bits -= p * Math.log2(p);
  }
  return bits;
}

/**
 * One word that reads like a password: 8–64 characters with lower and upper
 * case, a digit and a symbol. URLs, emails and paths are not passwords.
 */
function looksLikePassword(token) {
  if (token.length < 8 || token.length > 64) return false;
  if (/^[a-z][a-z0-9+.-]*:\/\//i.test(token) || /^[^@]+@[^@]+\.[a-z]{2,}$/i.test(token)) return false;
  if (/^[~/\\]/.test(token)) return false;
  return /[a-z]/.test(token) && /[A-Z]/.test(token) && /\d/.test(token) && /[^A-Za-z0-9_\-./:]/.test(token);
}

/** One long random-looking word, the shape of most API keys and tokens. */
function looksLikeRandomKey(token) {
  if (token.length < 20 || token.length > 200 || !/^[A-Za-z0-9+/=_-]+$/.test(token)) return false;
  const digits = (token.match(/\d/g) || []).length;
  // Keys mix digits in; names end in them (`Heading2`, `Build20260927`).
  if (/^[A-Za-z_-]+\d+$/.test(token)) return false;
  return /[a-z]/.test(token) && /[A-Z]/.test(token) && digits >= 2 && shannonBitsPerChar(token) >= 3.8;
}

/**
 * Why a copy looks like a secret (a short label), or null. Copies that
 * match are not kept in the clipboard history.
 */
function sensitiveKind(text) {
  if (typeof text !== "string") return null;
  const trimmed = text.trim();
  if (trimmed === "") return null;
  for (const [label, re] of SECRET_PATTERNS) if (re.test(trimmed)) return label;
  if (isRecoveryPhrase(trimmed)) return "recovery phrase";
  if (containsCardNumber(trimmed)) return "card number";
  if (!/\s/.test(trimmed)) {
    if (looksLikePassword(trimmed)) return "password";
    if (looksLikeRandomKey(trimmed)) return "key";
  }
  return null;
}

const REDACTED = "•••••";
const PEM_PRIVATE_KEY_BLOCK =
  /-----BEGIN [A-Z0-9 ]*PRIVATE KEY(?: BLOCK)?-----[\s\S]*?(?:-----END [A-Z0-9 ]*PRIVATE KEY(?: BLOCK)?-----|$)/g;
const SECRET_PATTERNS_GLOBAL = SECRET_PATTERNS.map(([, re]) => new RegExp(re.source, "g"));
// Brackets, quotes and separators around a word ("(Hunter2025!)," → Hunter2025!).
// Trimmed by index: a regex like /[…]+$/ backtracks quadratically on a long run.
const WORD_EDGE_CHARS = new Set("()[]{}<>\"'“”‘’,;");

/** Spans of 12+ BIP39 words in a row, list numbers ("1." "12)") allowed between them. */
function recoveryPhraseSpans(text) {
  const spans = [];
  let start = -1;
  let end = -1;
  let words = 0;
  const close = () => {
    if (words >= 12) spans.push([start, end]);
    start = -1;
    words = 0;
  };
  for (const match of text.matchAll(/\S+/g)) {
    const word = match[0].toLowerCase().replace(/^\d+[.)]?/, "").replace(/[.,;:]$/, "");
    if (word === "") continue;
    if (/^[a-z]+$/.test(word) && isBip39Word(word)) {
      if (start < 0) start = match.index;
      end = match.index + match[0].length;
      words += 1;
    } else {
      close();
    }
  }
  close();
  return spans;
}

/**
 * The text with anything secret-shaped replaced by "•••••": the formats
 * `sensitiveKind` knows (keys, tokens, private key blocks, card numbers,
 * recovery phrases) wherever they are, and single words that read like a
 * password or a random key. For text that is kept anyway, such as the words
 * read from a screenshot, so a secret in it doesn't become searchable.
 * → { text, redacted } (how many were replaced)
 */
function redactSecrets(input) {
  let text = typeof input === "string" ? input : "";
  let redacted = 0;
  const hide = () => {
    redacted += 1;
    return REDACTED;
  };
  text = text.replace(PEM_PRIVATE_KEY_BLOCK, hide);
  for (const re of SECRET_PATTERNS_GLOBAL) text = text.replace(re, hide);
  text = text.replace(CARD_RUN, (whole, before, run) => (isCardNumber(run) ? `${before}${hide()}` : whole));
  for (const [start, end] of recoveryPhraseSpans(text).reverse()) {
    text = `${text.slice(0, start)}${hide()}${text.slice(end)}`;
  }
  text = text.replace(/\S+/g, (word) => {
    let start = 0;
    let end = word.length;
    while (start < end && WORD_EDGE_CHARS.has(word[start])) start += 1;
    while (end > start && WORD_EDGE_CHARS.has(word[end - 1])) end -= 1;
    const core = word.slice(start, end);
    if (!core || !(looksLikePassword(core) || looksLikeRandomKey(core))) return word;
    return `${word.slice(0, start)}${hide()}${word.slice(end)}`;
  });
  return { text, redacted };
}

/**
 * What a Finder copy keeps. `copied`: [{ path, size }]. Photos become images
 * (up to MAX_PHOTO_FILE_MB); other files are kept only with `keepFiles` on
 * (up to MAX_KEPT_FILE_MB); anything else is skipped and stays a name in
 * text. At most MAX_FILES_PER_COPY are kept.
 */
function planCopiedFiles(copied, capture) {
  const plan = { images: [], files: [], skipped: [] };
  for (const { path: filePath, size } of copied) {
    const kept = plan.images.length + plan.files.length;
    if (kept >= MAX_FILES_PER_COPY) {
      plan.skipped.push(filePath);
    } else if (isImageFile(filePath)) {
      (size <= MAX_PHOTO_FILE_MB * MB ? plan.images : plan.skipped).push(filePath);
    } else if (capture.keepFiles && size <= MAX_KEPT_FILE_MB * MB) {
      plan.files.push(filePath);
    } else {
      plan.skipped.push(filePath);
    }
  }
  return plan;
}

function isFileMetadata(metadata) {
  return parseMetadata(metadata).type === "file";
}

function normalizeRetention(raw) {
  const r = raw && typeof raw === "object" ? raw : {};
  const keepDays = KEEP_DAYS_OPTIONS.includes(r.keepDays) ? r.keepDays : DEFAULT_RETENTION.keepDays;
  const maxImageMB = IMAGE_CAP_OPTIONS_MB.includes(r.maxImageMB)
    ? r.maxImageMB
    : DEFAULT_RETENTION.maxImageMB;
  return { keepDays, maxImageMB };
}

/**
 * Which clipboard entries retention removes. `entries`: { id, createdAt,
 * favorite, isImage, isFile, bytes }. Pinned (favorite) entries are never
 * removed. First anything older than `keepDays`; then, while images and kept
 * files use more than `maxImageMB`, the oldest unpinned of them. Pinned ones
 * still count towards the space, so they are kept by giving up older ones.
 */
function pickPruneIds(entries, { now, keepDays, maxImageMB }) {
  const doomed = new Set();
  if (keepDays > 0) {
    const cutoff = now - keepDays * DAY_MS;
    for (const e of entries) {
      if (!e.favorite && Date.parse(e.createdAt) < cutoff) doomed.add(e.id);
    }
  }
  if (maxImageMB > 0) {
    const cap = maxImageMB * MB;
    const images = entries.filter((e) => (e.isImage || e.isFile) && !doomed.has(e.id));
    let used = images.filter((e) => e.favorite).reduce((sum, e) => sum + (e.bytes || 0), 0);
    const newestFirst = images
      .filter((e) => !e.favorite)
      .sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt));
    for (const e of newestFirst) {
      if (used + (e.bytes || 0) > cap) doomed.add(e.id);
      else used += e.bytes || 0;
    }
  }
  return [...doomed];
}

const kindOfEntry = (e) => (e.isImage ? "image" : e.isFile ? "file" : "text");

/** Ids a "Clear" action removes: one kind (or all), optionally only older ones; pinned stay. */
function pickClearIds(entries, { kind = "all", olderThanDays = 0, now }) {
  const cutoff = olderThanDays > 0 ? now - olderThanDays * DAY_MS : Infinity;
  return entries
    .filter((e) => !e.favorite)
    .filter((e) => kind === "all" || kindOfEntry(e) === kind)
    .filter((e) => Date.parse(e.createdAt) < cutoff)
    .map((e) => e.id);
}

function formatBytes(bytes) {
  const n = Number(bytes) || 0;
  if (n < 1024) return `${n} B`;
  if (n < MB) return `${Math.round(n / 1024)} KB`;
  if (n < 1024 * MB) return `${n < 10 * MB ? (n / MB).toFixed(1) : Math.round(n / MB)} MB`;
  return `${(n / (1024 * MB)).toFixed(1)} GB`;
}

/** Stored text for an image entry: dimensions, plus the file name when it came from Finder. */
function imageEntryText({ width, height, fileName }) {
  const size = `[Image ${width}×${height}]`;
  return fileName ? `${size} ${fileName}` : size;
}

/** Stored text for a kept file (what search matches). */
function fileEntryText(fileName) {
  return `[File] ${fileName}`;
}

/** Markdown body of a note made from a kept file: a link to its copy in attachments/. */
function fileNoteBody(fileName, attachment) {
  return `[${fileName.replace(/[[\]]/g, "")}](${encodeURI(attachment)})`;
}

/** Markdown body of a note made from a clipboard image (attachment path relative to the note). */
function imageNoteBody(attachment) {
  return `![Clipboard image](${attachment})`;
}

/** File name for an attachment in the notes folder: a stable stem plus the image's extension. */
function attachmentFileName(stem, ext) {
  const safeStem = String(stem).replace(/[^\w.-]+/g, "-");
  const safeExt = /^\.[a-z0-9]+$/i.test(ext) ? ext.toLowerCase() : ".png";
  return `${safeStem}${safeExt}`;
}

/** Image attachments a note shows: `![…](attachments/x.png)` only, never paths out of the folder. */
function noteImageRefs(body) {
  const refs = [];
  const re = /!\[[^\]]*\]\(([^)\s]+)\)/g;
  let match;
  while ((match = re.exec(String(body ?? ""))) !== null) {
    let ref;
    try {
      ref = decodeURIComponent(match[1]);
    } catch {
      continue; // a malformed %-escape
    }
    if (isSafeAttachmentRef(ref) && !refs.includes(ref)) refs.push(ref);
  }
  return refs;
}

function isSafeAttachmentRef(ref) {
  if (typeof ref !== "string" || !ref.startsWith("attachments/")) return false;
  const name = ref.slice("attachments/".length);
  return name.length > 0 && !/[/\\]/.test(name) && !name.startsWith(".") && isImageFile(name);
}

module.exports = {
  IMAGE_EXTENSIONS,
  MAX_FILES_PER_COPY,
  MAX_PHOTO_FILE_MB,
  MAX_KEPT_FILE_MB,
  DEFAULT_CAPTURE,
  normalizeCapture,
  PRIVATE_CLIPBOARD_FORMATS,
  isPrivateClipboard,
  PASSWORD_MANAGER_BUNDLE_IDS,
  isPasswordManagerApp,
  TERMINAL_BUNDLE_IDS,
  isPrivateInputApp,
  sensitiveKind,
  redactSecrets,
  planCopiedFiles,
  isFileMetadata,
  fileEntryText,
  fileNoteBody,
  KEEP_DAYS_OPTIONS,
  IMAGE_CAP_OPTIONS_MB,
  DEFAULT_RETENTION,
  extensionOf,
  isImageFile,
  fileUrlToPath,
  parseFilenamesPlist,
  parseMetadata,
  isImageMetadata,
  normalizeRetention,
  pickPruneIds,
  pickClearIds,
  formatBytes,
  imageEntryText,
  imageNoteBody,
  attachmentFileName,
  noteImageRefs,
  isSafeAttachmentRef,
};
