/**
 * What the clipboard history never keeps: copies a password manager marks as
 * private (per platform), copies made in a password manager, and text that
 * looks like a password, key, token, card number or recovery phrase.
 */
import { describe, it, expect } from "vitest";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const pure = require("../../bridge/clipboard-pure.js");

function clipboardWith(formats: Record<string, Buffer | true>) {
  return {
    has: (format: string) => format in formats,
    readBuffer: (format: string) => {
      const value = formats[format];
      return value === true ? Buffer.alloc(0) : value ?? Buffer.alloc(0);
    },
  };
}

const dword = (n: number) => {
  const b = Buffer.alloc(4);
  b.writeUInt32LE(n, 0);
  return b;
};

describe("isPrivateClipboard", () => {
  it("honours the macOS nspasteboard markers and older ones", () => {
    for (const format of [
      "org.nspasteboard.ConcealedType",
      "org.nspasteboard.TransientType",
      "org.nspasteboard.AutoGeneratedType",
      "com.agilebits.onepassword",
    ]) {
      expect(pure.isPrivateClipboard({ platform: "darwin", ...clipboardWith({ [format]: true }) })).toBe(true);
    }
    expect(pure.isPrivateClipboard({ platform: "darwin", ...clipboardWith({ "public.utf8-plain-text": true }) })).toBe(false);
  });

  it("honours what KeePass, Bitwarden and 1Password set on Windows", () => {
    const win = (formats: Record<string, Buffer | true>) =>
      pure.isPrivateClipboard({ platform: "win32", ...clipboardWith(formats) });
    expect(win({ ExcludeClipboardContentFromMonitorProcessing: true })).toBe(true);
    expect(win({ "Clipboard Viewer Ignore": true })).toBe(true);
    expect(win({ CanIncludeInClipboardHistory: dword(0) })).toBe(true);
    expect(win({ CanUploadToCloudClipboard: dword(0) })).toBe(true);
    expect(win({ CanIncludeInClipboardHistory: dword(1) })).toBe(false);
    expect(win({ CanIncludeInClipboardHistory: Buffer.alloc(0) })).toBe(true); // unreadable: private
    expect(win({})).toBe(false);
  });

  it("honours KDE's password-manager hint on Linux (KeePassXC)", () => {
    expect(pure.isPrivateClipboard({ platform: "linux", ...clipboardWith({ "x-kde-passwordManagerHint": Buffer.from("secret") }) })).toBe(true);
    expect(pure.isPrivateClipboard({ platform: "linux", ...clipboardWith({}) })).toBe(false);
  });

  it("counts a copy as private when the check itself fails", () => {
    const has = () => {
      throw new Error("pasteboard busy");
    };
    expect(pure.isPrivateClipboard({ platform: "darwin", has, readBuffer: () => Buffer.alloc(0) })).toBe(true);
  });
});

describe("password managers and terminals", () => {
  it("knows copies made in a password manager", () => {
    expect(pure.isPasswordManagerApp({ name: "1Password", bundleId: "com.1password.1password" })).toBe(true);
    expect(pure.isPasswordManagerApp({ name: "Passwords", bundleId: "com.apple.Passwords" })).toBe(true);
    expect(pure.isPasswordManagerApp({ name: "Safari", bundleId: "com.apple.Safari" })).toBe(false);
    expect(pure.isPasswordManagerApp(undefined)).toBe(false);
  });

  it("never reads fields in terminals or password managers", () => {
    expect(pure.isPrivateInputApp("com.apple.Terminal")).toBe(true);
    expect(pure.isPrivateInputApp("com.googlecode.iterm2")).toBe(true);
    expect(pure.isPrivateInputApp("org.keepassxc.keepassxc")).toBe(true);
    expect(pure.isPrivateInputApp("com.tinyspeck.slackmacgap")).toBe(false);
    expect(pure.isPrivateInputApp(null)).toBe(false);
  });
});

describe("sensitiveKind", () => {
  it.each([
    ["sk-proj-abcdefghijklmnopqrstuvwxyz123456", "API key"],
    ["sk-ant-api03-abcdefghijklmnopqrstuvwxyz0123", "API key"],
    ["ANTHROPIC_API_KEY=sk-ant-abcdefghijklmnopqrstuvwx\nOTHER=1", "API key"],
    ["AKIAIOSFODNN7EXAMPLE", "AWS key"],
    ["ghp_abcdefghijklmnopqrstuvwxyz0123456789", "GitHub token"],
    ["xoxb-1234567890-abcdefghijk", "token"],
    ["eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U", "token"],
    ["-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXk=\n-----END OPENSSH PRIVATE KEY-----", "private key"],
    ["abandon ability able about above absent absorb abstract absurd abuse access accident", "recovery phrase"],
    ["4111 1111 1111 1111", "card number"],
    ["My card: 4111-1111-1111-1111 exp 12/29", "card number"],
    ["Pa$$w0rd123", "password"],
    ["xK9mP2vLq8Rt5Zw3Nc7Bd4Hj", "key"],
  ])("does not keep %j (%s)", (text, kind) => {
    expect(pure.sensitiveKind(text)).toBe(kind);
  });

  it.each([
    "hello world",
    "The meeting is at 3pm, room B12",
    "camelCaseVariableName",
    "ThisIsMyVariableName123456",
    "iPhone15ProMax",
    "https://example.com/a?b=1&c=Dd9!",
    "user@example.com",
    "/Users/me/Documents/Report 2026.pdf",
    "4874ab2",
    "3f2a1c9e8b7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f",
    "550e8400-e29b-41d4-a716-446655440000",
    "2026-09-27",
    "Order 1234567890123 shipped",
    "SELECT * FROM users WHERE id=1",
    "abandon ability able about", // four words is not a phrase
    "",
  ])("keeps ordinary text %j", (text) => {
    expect(pure.sensitiveKind(text)).toBe(null);
  });
});

describe("redactSecrets (words read from a screenshot)", () => {
  const hidden = (text: string) => pure.redactSecrets(text).text;

  it("hides keys and tokens but keeps the words around them", () => {
    expect(hidden("OPENAI_API_KEY=sk-proj-abcdefghijklmnopqrstuvwxyz0123 is set")).toBe("OPENAI_API_KEY=••••• is set");
    expect(hidden("Token ghp_abcdefghijklmnopqrstuvwxyz0123456789 copied\nAKIAIOSFODNN7EXAMPLE")).toBe(
      "Token ••••• copied\n•••••"
    );
    expect(pure.redactSecrets("a sk-ant-abcdefghijklmnopqrstuv0123 b sk-ant-zyxwvutsrqponmlkjihgf9876").redacted).toBe(2);
  });

  it("hides a whole private key block, even one cut off at the edge of the screenshot", () => {
    const key = "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmU\n-----END OPENSSH PRIVATE KEY-----";
    expect(hidden(`id_ed25519\n${key}\nSave`)).toBe("id_ed25519\n•••••\nSave");
    expect(hidden("-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA\nqk3")).toBe("•••••");
  });

  it("hides card numbers, recovery phrases and password-like words", () => {
    expect(hidden("Card 4242 4242 4242 4242 exp 12/28")).toBe("Card ••••• exp 12/28");
    expect(hidden("Order 1234567890123 shipped")).toBe("Order 1234567890123 shipped"); // not Luhn-valid
    const grid =
      "Recovery phrase\n1. abandon 2. ability 3. able 4. about\n5. above 6. absent 7. absorb 8. abstract\n9. absurd 10. abuse 11. access 12. accident\nDone";
    expect(hidden(grid)).toBe("Recovery •••••\nDone"); // "phrase" is a BIP39 word too
    expect(hidden("Wi-Fi password: (Hunter2025!),")).toBe("Wi-Fi password: (•••••),");
    expect(hidden("secret aB3dE5fG7hJ9kL1mN3pQ5rS7tU9vW")).toBe("secret •••••");
  });

  it("leaves ordinary screenshot text alone", () => {
    const text = [
      "macOS 14.2 (23C64) iPhone 15 Pro, Windows11 COVID-19 SHA-256",
      "user@example.com https://github.com/h3qing/WhisperWoof/pull/141?tab=files&q=Dd9!",
      "现在真正的瓶颈 +1 (415) 555-0100 2026-09-27 19:03 Version 2.4.0",
      "eaa8e75bcfdf240a396e02647146f36b5bb564c8 550e8400-e29b-41d4-a716-446655440000",
      "abandon ability able about above", // five BIP39 words is not a phrase
    ].join("\n");
    expect(pure.redactSecrets(text)).toEqual({ text, redacted: 0 });
    expect(pure.redactSecrets(undefined)).toEqual({ text: "", redacted: 0 });
  });

  it("stays fast on text made to make a regex backtrack (an image anyone could have made)", () => {
    for (const text of ["x" + "(".repeat(20000) + "x", "a" + ",".repeat(20000) + "b", "4 ".repeat(10000)]) {
      const started = performance.now();
      pure.redactSecrets(text);
      expect(performance.now() - started).toBeLessThan(100);
    }
  });

  it("is idempotent", () => {
    const once = hidden("key sk-proj-abcdefghijklmnopqrstuvwxyz0123 and 4242 4242 4242 4242");
    expect(pure.redactSecrets(once)).toEqual({ text: once, redacted: 0 });
  });
});

describe("normalizeCapture", () => {
  it("keeps monitoring on unless it was turned off", () => {
    expect(pure.normalizeCapture(undefined)).toEqual({ keepFiles: false, monitor: true });
    expect(pure.normalizeCapture({ keepFiles: true })).toEqual({ keepFiles: true, monitor: true });
    expect(pure.normalizeCapture({ monitor: false })).toEqual({ keepFiles: false, monitor: false });
    expect(pure.normalizeCapture({ monitor: "no" })).toEqual({ keepFiles: false, monitor: true });
  });
});
