/**
 * What the clipboard history never keeps: copies a password manager marks as
 * private (per platform), copies made in a password manager, and text that
 * looks like a password, key, token, card number or recovery phrase.
 */
import { describe, it, expect } from "vitest";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const pure = require("../../bridge/clipboard-pure.js");

function clipboardWith(formats: Record<string, Buffer | true>) {
  return {
    has: (format: string) => format in formats,
    readBuffer: (format: string) => {
      const value = formats[format];
      return value === true ? Buffer.alloc(0) : value ?? Buffer.alloc(0);
    },
  };
}

const dword = (n: number) => {
  const b = Buffer.alloc(4);
  b.writeUInt32LE(n, 0);
  return b;
};

describe("isPrivateClipboard", () => {
  it("honours the macOS nspasteboard markers and older ones", () => {
    for (const format of [
      "org.nspasteboard.ConcealedType",
      "org.nspasteboard.TransientType",
      "org.nspasteboard.AutoGeneratedType",
      "com.agilebits.onepassword",
    ]) {
      expect(pure.isPrivateClipboard({ platform: "darwin", ...clipboardWith({ [format]: true }) })).toBe(true);
    }
    expect(pure.isPrivateClipboard({ platform: "darwin", ...clipboardWith({ "public.utf8-plain-text": true }) })).toBe(false);
  });

  it("honours what KeePass, Bitwarden and 1Password set on Windows", () => {
    const win = (formats: Record<string, Buffer | true>) =>
      pure.isPrivateClipboard({ platform: "win32", ...clipboardWith(formats) });
    expect(win({ ExcludeClipboardContentFromMonitorProcessing: true })).toBe(true);
    expect(win({ "Clipboard Viewer Ignore": true })).toBe(true);
    expect(win({ CanIncludeInClipboardHistory: dword(0) })).toBe(true);
    expect(win({ CanUploadToCloudClipboard: dword(0) })).toBe(true);
    expect(win({ CanIncludeInClipboardHistory: dword(1) })).toBe(false);
    expect(win({ CanIncludeInClipboardHistory: Buffer.alloc(0) })).toBe(true); // unreadable: private
    expect(win({})).toBe(false);
  });

  it("honours KDE's password-manager hint on Linux (KeePassXC)", () => {
    expect(pure.isPrivateClipboard({ platform: "linux", ...clipboardWith({ "x-kde-passwordManagerHint": Buffer.from("secret") }) })).toBe(true);
    expect(pure.isPrivateClipboard({ platform: "linux", ...clipboardWith({}) })).toBe(false);
  });

  it("counts a copy as private when the check itself fails", () => {
    const has = () => {
      throw new Error("pasteboard busy");
    };
    expect(pure.isPrivateClipboard({ platform: "darwin", has, readBuffer: () => Buffer.alloc(0) })).toBe(true);
  });
});

describe("password managers and terminals", () => {
  it("knows copies made in a password manager", () => {
    expect(pure.isPasswordManagerApp({ name: "1Password", bundleId: "com.1password.1password" })).toBe(true);
    expect(pure.isPasswordManagerApp({ name: "Passwords", bundleId: "com.apple.Passwords" })).toBe(true);
    expect(pure.isPasswordManagerApp({ name: "Safari", bundleId: "com.apple.Safari" })).toBe(false);
    expect(pure.isPasswordManagerApp(undefined)).toBe(false);
  });

  it("never reads fields in terminals or password managers", () => {
    expect(pure.isPrivateInputApp("com.apple.Terminal")).toBe(true);
    expect(pure.isPrivateInputApp("com.googlecode.iterm2")).toBe(true);
    expect(pure.isPrivateInputApp("org.keepassxc.keepassxc")).toBe(true);
    expect(pure.isPrivateInputApp("com.tinyspeck.slackmacgap")).toBe(false);
    expect(pure.isPrivateInputApp(null)).toBe(false);
  });
});

describe("sensitiveKind", () => {
  it.each([
    ["sk-proj-abcdefghijklmnopqrstuvwxyz123456", "API key"],
    ["sk-ant-api03-abcdefghijklmnopqrstuvwxyz0123", "API key"],
    ["ANTHROPIC_API_KEY=sk-ant-abcdefghijklmnopqrstuvwx\nOTHER=1", "API key"],
    ["AKIAIOSFODNN7EXAMPLE", "AWS key"],
    ["ghp_abcdefghijklmnopqrstuvwxyz0123456789", "GitHub token"],
    ["xoxb-1234567890-abcdefghijk", "token"],
    ["eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U", "token"],
    ["-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXk=\n-----END OPENSSH PRIVATE KEY-----", "private key"],
    ["abandon ability able about above absent absorb abstract absurd abuse access accident", "recovery phrase"],
    ["4111 1111 1111 1111", "card number"],
    ["My card: 4111-1111-1111-1111 exp 12/29", "card number"],
    ["Pa$$w0rd123", "password"],
    ["xK9mP2vLq8Rt5Zw3Nc7Bd4Hj", "key"],
  ])("does not keep %j (%s)", (text, kind) => {
    expect(pure.sensitiveKind(text)).toBe(kind);
  });

  it.each([
    "hello world",
    "The meeting is at 3pm, room B12",
    "camelCaseVariableName",
    "ThisIsMyVariableName123456",
    "iPhone15ProMax",
    "https://example.com/a?b=1&c=Dd9!",
    "user@example.com",
    "/Users/me/Documents/Report 2026.pdf",
    "4874ab2",
    "3f2a1c9e8b7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f",
    "550e8400-e29b-41d4-a716-446655440000",
    "2026-09-27",
    "Order 1234567890123 shipped",
    "SELECT * FROM users WHERE id=1",
    "abandon ability able about", // four words is not a phrase
    "",
  ])("keeps ordinary text %j", (text) => {
    expect(pure.sensitiveKind(text)).toBe(null);
  });
});

describe("normalizeCapture", () => {
  it("keeps monitoring on unless it was turned off", () => {
    expect(pure.normalizeCapture(undefined)).toEqual({ keepFiles: false, monitor: true });
    expect(pure.normalizeCapture({ keepFiles: true })).toEqual({ keepFiles: true, monitor: true });
    expect(pure.normalizeCapture({ monitor: false })).toEqual({ keepFiles: false, monitor: false });
    expect(pure.normalizeCapture({ monitor: "no" })).toEqual({ keepFiles: false, monitor: true });
  });
});
